#!/bin/bash
# geth initializing
if [ $1 = "init" ]; then
    mkdir -p ~/private_net
    cat > ~/private_net/genesis.json << EOF
{
    "config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "difficulty": "10",
    "gasLimit": "2100000",
    "alloc" : {}
}
EOF
    geth --datadir ~/private_net/ init ~/private_net/genesis.json
fi
# geth run
if [ $1 = "run" ]; then
    priv_addr=`ifconfig | grep "inet addr" | grep 192 | awk '{print $2}' | sed -e 's/^.*://g'`
    geth --networkid "15" --datadir "~/private_net" --rpc --rpcaddr "$priv_addr" --rpcport "8545" --rpcapi "web3, eth, net, personal" --rpccorsdomain "*" console
fi
# geth attach
if [ $1 = "attach" ]; then
    geth attach ipc:$HOME/private_net/geth.ipc
fi
